services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile 
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    expose:
      - "3306"
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    expose:
      - "9000"
    restart: on-failure

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: '/home/inception-user/data/mariadb'
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: '/home/inception-user/data/wordpress'
      o: bind

networks:
  inception_network:
    driver: bridge